# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections_dir: pages
collections:
  en:
    output: true
    permalink: /:path/
  fr:
    output: true
    permalink: /:path/
  homepage:
    output: true
    permalink: /:path/
  menu:
    output: false

# Title
name: Find financial help during COVID-19
subtitle: Help Canadians find benefits they may be eligible for during Covid-19

baseurl: "/c19-benefits-prestations-docs"

# Author/Organization info to be displayed in the templates
author:
  name: Canadian Digital Service
  url: https://digital.canada.ca
author2:
  name: Treasury Board of Canada Secretariat
  url: https://www.canada.ca/en/treasury-board-secretariat.html

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# List repos that you would like to appear on the homepage here
repos:
  - name: c19-benefits-prestations-docs

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
