# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections_dir: pages
collections:
  en:
    output: true
    permalink: /:path/
  fr:
    output: true
    permalink: /:path/
  menu:
    output: false

# Title
name: Claim tax benefits documentation
subtitle: Help low-income Canadians file taxes to access their benefits

baseurl: "/claim-tax-benefits-documentation"

# Author/Organization info to be displayed in the templates
author:
  name: Canadian Digital Service
  url: https://digital.canada.ca
author2:
  name: Treasury Board of Canada Secretariat
  url: https://www.canada.ca/en/treasury-board-secretariat.html

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# List repos that you would like to appear on the homepage here
repos:
  - name: cra-claim-tax-benefits

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
