# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'
collections:
  - name: 'docEn'
    label: 'Documentation - EN'
    folder: '_pages/en'
    sort: "title:asc"
    create: true
    permalink: /en/:title
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Lang", name: "lang", widget: "hidden", default: "en"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - label: "Translation url"
        name: "trans_url"
        widget: "relation"
        collection: "docFr"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title", "permalink"]
  - name: 'docFr'
    label: 'Documentation - FR'
    folder: '_pages/fr'
    sort: "title:asc"
    create: true
    permalink: /fr/:title
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Adresse pour la traduction", name: "trans_url", widget: "string"}
      - {label: "Lang", name: "lang", widget: "hidden", default: "en"}
      - {label: "Corps du texte", name: "body", widget: "markdown", required: true}
